### PR TITLE
Fix make install error

### LINKED ISSUE #6: make install target fails
@cpinter @TrosnyogoSzakoca 

There seems to be something fishy with the "make install" CMake target.

I get:

```
make
[ 50%] Linking CXX shared library libvtkIECTransformLogic.so
[100%] Built target vtkIECTransformLogic
find ./ -name libvtkIECTransformLogic.so
./libvtkIECTransformLogic.so
make install
Consolidate compiler generated dependencies of target vtkIECTransformLogic
[100%] Built target vtkIECTransformLogic
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:60 (file):
  file INSTALL cannot find
  "/opt/RadiotherapyTransformsIEC/build/libvtkIECTransformLogic.so": No such
  file or directory.
find ./ -name libvtkIECTransformLogic.so
No return ---> File has been removed by "make install" somehow
```

### PR DESCRIPTION
**Pull request by ferdymercury**
This change seems to fix the error when calling "make install", but I do not know if it has side effects.

Fixes https://github.com/EBATINCA/RadiotherapyTransformsIEC/issues/6

### CODE REVIEW

**Comment by cpinter** [comment]
I cannot really assess the consequences of this change. Feel free to do the rebase and merge. We'll have the commit in the history if it turns out to have some undesired effect. If the commit message contains this suspicion, this is more explicit.

**Comment by ferdymercury** [comment]
Thanks. I'll try first to see if this breaks the "build from within Slicer" variant. At the moment I have just tested as standalone install.

**Comment by ferdymercury** [comment]
Ok, it seems that SlicerRt builds fine with this step (at least on Linux, no idea about Windows), probably because "install" is not called directly. I will not merge yet because there are some other outstanding issues with installing not copying the header files.

But first, I had one question for my knowledge: there are several files in the project whose purpose I am not super sure about.
Are these files strictly required for any library that SlicerRt depends on? In particular:

```
vtkIECTransformLogicConfig.cmake.in
vtkIECTransformLogicConfigure.h.in
vtkIECTransformLogicExport.h
vtkIECTransformLogicInstallConfig.cmake.in
CMake/vtkIECTransformLogicFunctionAddExecutable.cmake
CMake/vtkMacroKitPythonWrap.cmake
CMake/vtkWrapHierarchy.cmake
CMake/vtkWrapperInit.data.in
CMake/vtkWrapPython.cmake
CMake/WindowsApplicationUseUtf8.manifest
```

and the corresponding snippepts in the CMakeLists:

```
# --------------------------------------------------------------------------
# Python Wrapping
# --------------------------------------------------------------------------
if(vtkIECTransformLogic_WRAP_PYTHON)
...

# Install vtkIECTransformLogic CMake files
install(
  FILES
  ${vtkIECTransformLogic_CMAKE_DIR}/vtkIECTransformLogicFunctionAddExecutable.cmake
  ${vtkIECTransformLogic_CMAKE_DIR}/vtkIECTransformLogicFunctionAddExecutable.cmake
  ${vtkIECTransformLogic_CMAKE_DIR}/vtkMacroKitPythonWrap.cmake
  ${vtkIECTransformLogic_CMAKE_DIR}/vtkWrapHierarchy.cmake
  ${vtkIECTransformLogic_CMAKE_DIR}/vtkWrapperInit.data.in
  ${vtkIECTransformLogic_CMAKE_DIR}/vtkWrapPython.cmake
  ${vtkIECTransformLogic_CMAKE_DIR}/WindowsApplicationUseUtf8.manifest
  DESTINATION ${${PROJECT_NAME}_INSTALL_CMAKE_DIR} COMPONENT Development
  )


include(CMakeDependentOption)
include(vtkIECTransformLogicFunctionAddExecutable)



# if(NOT DEFINED BUILD_SHARED_LIBS)
#   option(BUILD_SHARED_LIBS "Build with shared libraries." ON)
# endif()

# if(NOT DEFINED BUILD_TESTING)
#   option(BUILD_TESTING "Test the project" OFF)
# endif()

# if(NOT DEFINED vtkIECTransformLogic_USE_UTF8)
#   option(vtkIECTransformLogic_USE_UTF8 "Make applications use UTF-8 as code page." OFF)
# endif()

# if(NOT DEFINED vtkIECTransformLogic_WRAP_PYTHON)
#   cmake_dependent_option(vtkIECTransformLogic_WRAP_PYTHON "Build python wrapping" OFF "VTK_WRAP_PYTHON" OFF)
# endif()

# if(NOT DEFINED vtkIECTransformLogic_LAUNCH_COMMAND)
#   set(vtkIECTransformLogic_LAUNCH_COMMAND "" CACHE STRING "Command for setting up environment and running executables")
# endif()
```

**Comment by cpinter** [comment]
Great that SlicerRT builds! It did before as far as I know, but cannot find symbols at runtime.

Many of those files are for Python wrapping, without which it cannot really be a fully equipped library. Some others are for using it as external project in CMake and exporting the symbols.

**Comment by ferdymercury** [comment]
> It did before as far as I know, but cannot find symbols at runtime.

Yep, I was speaking only about Linux, runtime is also fine. Most probably in Windows the problem is still there.

**Pull request closed without merging**
